name: Build and Test

on:
  pull_request:
    branches:
      - dev
      - qa
      - production


jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      statuses: write
      packages: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build
#        env:
#          GPR_USER: ${{ secrets.GPR_USER }}
#          GPR_TOKEN: ${{ secrets.GPR_TOKEN }}

      - name: Test with Gradle
        run: ./gradlew test
#        env:
#          GPR_USER: ${{ secrets.GPR_USER }}
#          GPR_TOKEN: ${{ secrets.GPR_TOKEN }}
