---

name: Linter

on:
  pull_request:
    branches:
      - development
      - staging
      - production

jobs:
  build:
    name: Linter
    runs-on: self-hosted

    permissions:
      contents: read
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Lint
        uses: super-linter/super-linter/slim@v6.2.0
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_GOOGLE_JAVA_FORMAT: false
          VALIDATE_CHECKOV: false
          VALIDATE_BASH: false
          VALIDATE_BASH_EXEC: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_SHELL_SHFMT: false
          VALIDATE_SQLFLUFF: false
          VALIDATE_GROOVY: false
          FILTER_REGEX_EXCLUDE: sonar-project.properties
          LINTER_RULES_PATH: .github/linters
          JAVA_FILE_NAME: sun_checks.xml
          DEFAULT_BRANCH: production
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
