name: SonarQube Analysis

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

#      - name: Configure Gradle properties
#        run: |
#          mkdir -p $HOME/.gradle
#          cp gradle.properties $HOME/.gradle/gradle.properties
#        env:
#          JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/17.0.12-7/x64
#          JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Adopt_jdk/17.0.12-7/x64

      - name: Test with Gradle
        run: ./gradlew test jacocoTestReport
#        env:
#          GPR_USER: ${{ secrets.GPR_USER }}
#          GPR_TOKEN: ${{ secrets.GPR_TOKEN }}

      - name: Build with Gradle
        run: ./gradlew build
#        env:
#          GPR_USER: ${{ secrets.GPR_USER }}
#          GPR_TOKEN: ${{ secrets.GPR_TOKEN }}

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://zaggle-sonar.zaggle.info/

#      - name: Check Code Coverage
#        run: |
#          COVERAGE=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "https://zaggle-sonar.zaggle.info/api/measures/component?component=ems-admin-java&metricKeys=new_coverage" | jq -r '.component.measures[0].period.value')
#          echo "Code coverage: $COVERAGE%"
#          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
#            echo "Code coverage is less than 80%. Failing the job."
#            echo "https://zaggle-sonar.zaggle.info/dashboard?id=ems-admin-java"
#            exit 1
#          else
#            echo "Code coverage is greater than or equal to 80%. Success."
#          fi
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
